### ISSUE TITLE
On mobile, after screen rotation to landscape, then back to portrait, the graphics don't resize properly to container

### ISSUE THREAD

**Issue by shmcminn** [nprapps/dailygraphics-next#11]
Also seems to be happening with interactive-template

Tested on Safari

**Comment by thomaswilburn** [comment]
Fixed via https://github.com/nprapps/dailygraphics-templates/commit/0b7d57bc171f6b6952236bff37c368d82bd68679

Please pull the updated templates repo
@shmcminn @alykat @reneeklahr @nunderwood6
