### ISSUE TITLE
creating new annotated line chart doesn't clone google sheet template

### ISSUE THREAD

**Issue by stiles** [nprapps/dailygraphics-next#15]
I recently started using this newer version of the dailygraphics rig (which is super, btw), but I'm having trouble getting a new line chart to load. 

When I create the graphic, and try to render it locally in the admin, I get an error in the CLI saying the Google Sheet can't be accessed. 

Perhaps the sheet template is protected for users outside NPR Apps? (I'm not having the same problem with, say, a column chart or bar chart. Those work just fine). 

```Connected to Google as Matt Stiles
_content.html:8 39
Template execution error: _content.html:1
<% if (COPY.labels.headline) { %>
<h1><%= t.smarty(COPY.labels.headline) %></h1>
<% } %>
ERROR:  Error in undefined: Cannot read property 'headline' of undefined
```

<img width="713" alt="Screen Shot 2019-05-07 at 9 17 43 PM" src="https://user-images.githubusercontent.com/232237/57349102-b06da500-710d-11e9-980d-8c551355feff.png">

<img width="1404" alt="Screen Shot 2019-05-07 at 9 17 12 PM" src="https://user-images.githubusercontent.com/232237/57349103-b06da500-710d-11e9-8a35-9aeb970466f8.png">

As you can see, I don't have the same problem when I test a bar chart (also note that the admin has an icon linking to the sheet itself, and the one that loads for the line chart doesn't): 

<img width="1431" alt="Screen Shot 2019-05-07 at 9 30 02 PM" src="https://user-images.githubusercontent.com/232237/57349537-5837a280-710f-11e9-98be-4493aa95e42c.png">

**Comment by stiles** [comment]
The `manifest.json` file looks like this: 

```
{
  "templateSheet": "1wq0oi5HfgfYBdDs32-Qs77xmnI9VMXPUgRHA8lKIRmM",
  "files": [
    "index.html",
    "graphic.js",
    "graphic.less",
    "*.png",
    "*.jpg",
    "*.json",
    "!manifest.json",
    "*.geojson",
    "*.csv"
  ]
}
```

I get this when I try to [load that sheet](https://docs.google.com/spreadsheets/d/1wq0oi5HfgfYBdDs32-Qs77xmnI9VMXPUgRHA8lKIRmM) from the browser in Google Drive: 

![Uploading Screen Shot 2019-05-07 at 9.27.08 PM.png…]()

**Comment by alykat** [comment]
Thanks for flagging this. Try again? Public users should have view rights to that sheet.

**Comment by stiles** [comment]
Working now. Thanks! 

![Screen Shot 2019-05-08 at 2 09 02 PM](https://user-images.githubusercontent.com/232237/57408604-f0c73480-719a-11e9-89df-050e2f2514ed.png)
