### ISSUE TITLE
When editing LESS, live reload works on `sheets-v4` but not `master`

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics-next#17]
Brand-new weirdness: When I'm on the `master` branch and edit LESS files, the related page doesn't auto-reload. I have to restart the local server to see the change.

When I'm on the `sheets-v4` branch, everything works fine.

**Comment by thomaswilburn** [comment]
Yes, I broke this yesterday on a bug for Sean, and I think I fixed it tonight while demoing for the Chicago ONA Meetup. Pull and try again?

**Comment by alykat** [comment]
Yep, everything's good now.
