### ISSUE TITLE
Handle large media assets

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics-next#2]
The Dailygraphics Classic rig includes an [assets rig](https://github.com/nprapps/dailygraphics#storing-media-assets) for syncing larger files (audio files, large images, original versions of files) to S3. How might this this might work in Dailygraphics Next?

Options might include reproducing elements of the existing rig, evaulating [Git LFS](https://git-lfs.github.com/) (though the versioning element may not be what we want, [given the quota limitations](https://help.github.com/articles/about-storage-and-bandwidth-usage/)) or something else entirely?

Edited to note @thomaswilburn's observation that there are some native S3 sync functions that we could investigate:
https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html

**Comment by thomaswilburn** [comment]
Added a CLI command to sync a subfolder for graphics with S3 (6400191). We may add a UI for this if it's something we use more often.
