### ISSUE TITLE
Using require() in EJS templates

### ISSUE THREAD

**Issue by phjudge** [nprapps/dailygraphics-next#22]
It'd be nice to be able to use arbitrary JavaScript in the EJS templates themselves via `require()`.

Currently, if I want to add a template filter to my `_content.html`, I need to modify the rig's `templateFilters.js`.

By adding a `require()` filter, I can define a new template filter within the graphic itself instead of having to modify the rig.

For example:
```ejs
<% const md = t.require('markdown-it')(); %>

<% if (COPY.labels.headline) { %>
<h1><%= md.renderInline(COPY.labels.headline) %></h1>
<% } %>
```

## Implementation
This implementation is based on [chriscalo/ejs-require](https://github.com/chriscalo/ejs-require).

In the rig's `lib/processHTML.js`:
```js
var { createRequireFromPath } = require("module");

...

var t = Object.assign(
    {
      ...,
      require: createRequireFromPath(path.join(path.dirname(dir), "node_modules")),
    },
    filters
  );
```

NOTE: [`module.createRequireFromPath`](https://nodejs.org/dist/latest-v12.x/docs/api/modules.html#modules_module_createrequirefrompath_filename) was added to Node v10.12.0. It's been replaced with [`module.createRequire`](https://nodejs.org/dist/latest-v12.x/docs/api/modules.html#modules_module_createrequire_filename) since v12.2.0.

**Comment by thomaswilburn** [comment]
Hm, I'll check that out. The Interactive Template has historically supported calling `require()` from EJS, but it just passes the existing `require` in to the template, which probably does mean the paths are a little weird (and would be even weirder in DG-Next). I didn't know `createRequire*` existed, which would have been handy.

**Comment by thomaswilburn** [comment]
Actually, looking through `processHTML`, it probably makes more sense to just pass in the created `require()` as a top-level scope value, the same way we do with the `t` collection.

**Comment by phjudge** [comment]
Many thanks, @thomaswilburn!
