### ISSUE TITLE
Multi-page embed codes need unique IDs

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics-next#32]
The embed code output by the new multi-page preview template uses the same `id` for each embed. For example, for issue tracker, all the embeds get

```
id="responsive-embed-issue-tracker-20190903"
```

When multiple embeds exist on the same page, each `id` needs to be unique. For Issue Tracker, I'm using the slug and the part of the filename that's before `.html`, so:

```
id="responsive-embed-issue-tracker-20190903-health-care"
id="responsive-embed-issue-tracker-20190903-climate"
id="responsive-embed-issue-tracker-20190903-immigration"
```

(Granted, Issue Tracker embeds are intended to be standalone, but that's not the case for all projects like this.)

**Comment by thomaswilburn** [comment]
Fixed in 3702460. Pull from dailygraphics-templates as well.
