### ISSUE TITLE
Configurable server address

### ISSUE THREAD

**Issue by jakekara** [nprapps/dailygraphics-next#4]
This may be outside the scope of how you're interested in using this app. Or I might be missing something super obvious...

It's possible (and in my newsroom's case, preferable) to modify the server address in lib.googleAuth.getClient and run this on a remote server instead of localhost, but the server address could be parameterized instead of hard-coded. I'm trying to figure out how to parameterize it in a way that maintains the conventions used throughout the project.

The getClient function appears to take a custom redirect url as a parameter, but that feature is unused because none of the calls to it (lib.sheetOps.getSheet, for instance) seem to accept or pass along server info.

By convention it doesn't look like any of the lib functions read config.json directly, but some accept a config object, like lib.deployGraphic.js and lib.createGraphic. 

So these functions, deployGraphic and createGraphic, could be made to pass along the custom redirect URL from config to getSheet, createSheet, etc, and those could be made to pass it along to getClient. But that's a lot of modifications.

I think the most conventional way would be to make this an environmental variable. (Proposal: GOOGLE_REDIRECT_URL). This does break the convention of using env only for "sensitive" information, but googleAuth.js already reads environmental variables so it wouldn't require modifying any lib API functions.

**Comment by thomaswilburn** [comment]
Are you looking to change the entire redirect URL (including path and host), or just the domain?

I think the only place you'd actually need to change the code to update, and which would have access to the config object, would be in the `googleAuth` handler, which is the only place where the OAuth2 client actually uses that redirect. Everywhere else, it's passed to the client just in case, but overridden by the credentials loaded from the token file.

I don't think it's a bad idea to have a customizable hostname. We could do it from the config object, or treat it like the port is treated, and handle it with a CLI switch.

**Comment by thomaswilburn** [comment]
On a side note, using this in a hosted fashion is not _technically_ supported, although I am interested in how it works for you. Generally, the plan with the REST server was to make the local experience more pleasant, not create a true hosted admin. There are some other places where I think you may hit issues, like spontaneous live reload events when another person creates a graphic while a second person is previewing an existing page.

**Comment by jakekara** [comment]
Just the domain would be good (though getClient takes a full redirect_url parameter).

On that side note, yeah I figure there will be some weird issues running this as a service -- particularly, it needs to be security hardened -- and if you only need it locally, there's no point going down that massive rabbit hole. But this project is the closest approximation to what I (and probably a lot of local coders) need than anything else I've seen: I need to be able to templatize my graphics and have every newsroom member (not just technical people who can run node) able to use the tools.

Maybe a better approach would be to package the entire app into a standalone executable, with something like pkg? (https://github.com/zeit/pkg)

**Comment by thomaswilburn** [comment]
Yeah, we can build the redirect URI from the domain and the port (the path is not, at this time, something I'm interested in customizing, since it would require us to also rewrite the routing code). I'll see if I can put something together this week.
