### ISSUE TITLE
d3-selection circular dependency errors since switch to rollup

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics-next#55]
Seeing a lot of this in console since we switched over to rollup for bundling:

```
Circular dependency: ../graphics-js/node_modules/d3-selection/src/selection/index.js -> ../graphics-js/node_modules/d3-selection/src/selection/data.js -> ../graphics-js/node_modules/d3-selection/src/selection/index.js
Circular dependency: ../graphics-js/node_modules/d3-selection/src/selection/index.js -> ../graphics-js/node_modules/d3-selection/src/selection/data.js -> ../graphics-js/node_modules/d3-selection/src/selection/enter.js -> ../graphics-js/node_modules/d3-selection/src/selection/index.js
Circular dependency: ../graphics-js/node_modules/d3-selection/src/selection/index.js -> ../graphics-js/node_modules/d3-selection/src/selection/exit.js -> ../graphics-js/node_modules/d3-selection/src/selection/index.js
Circular dependency: ../graphics-js/node_modules/d3-selection/src/selection/index.js -> ../graphics-js/node_modules/d3-selection/src/selection/merge.js -> ../graphics-js/node_modules/d3-selection/src/selection/index.js
Circular dependency: ../graphics-js/node_modules/d3-selection/src/selection/index.js -> ../graphics-js/node_modules/d3-selection/src/selection/sort.js -> ../graphics-js/node_modules/d3-selection/src/selection/index.js
```

Seems to be annoying but benign? Will try the approach mentioned here to suppress the warning: https://github.com/d3/d3-selection/issues/168

**Comment by thomaswilburn** [comment]
That's effectively what we ended up doing: https://github.com/Chalkbeat/dailygraphics-next/commit/1beab0f9b3758988e8a4a923e34b344cb77deb34

Circular dependencies are allowed by ES modules, so it's not technically an error, and D3 is unlikely to change anytime soon.

**Comment by thomaswilburn** [comment]
(You may also want to pull the sync changes that I added after realizing that missing directories on either side would throw warnings: https://github.com/Chalkbeat/dailygraphics-next/commit/a7bdb68f549dff70d083afe851424e384f31dd9d)

**Comment by alykat** [comment]
@thomaswilburn ah great! thank you! starting on that here — https://github.com/nprapps/dailygraphics-next/tree/ah-sync-crashes. will test and probably merge in the morning.
