### ISSUE TITLE
Trouble with fs.promises API using node v10.0.0

### ISSUE THREAD

**Issue by eidietrich** [nprapps/dailygraphics-next#6]
Possibly something to add to the troubleshooting section — trying to get this running on my machine (Macbook running Mojave) today I ran into errors apparently caused by the fs.promises API.

It showed up initially as an ```UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'graphicsPath' of null``` when I ran ```npm start``` at step 5 of the Quickstart guide. It looks like what was happening was that the ```var fs = require("fs").promises;``` line in ```./lib/readJSON.js``` wasn't resolving, meaning the server couldn't read the config file.

Updating Node from v10.0.0 to v.10.15.0 appears to have fixed things for me, but it might be worth flagging in the documentation since Node does have fs.promises [marked experimental](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html).

**Comment by thomaswilburn** [comment]
Thanks, I'll update the readme.
